"""Unit tests for Intellectual Routing — the Deep Research multi-model relay.

Covers the `_deep_research_relay` core and both entry points
(`route_deep_research`, `route_deep_research_stream`) with a scripted fake
provider and DB, so no network or database is required. Maps to the
intellectual-routing spec tasks 8.2 (relay behavior + entry-point parity).
"""
import asyncio

import pytest

from app.services import fallback_router as fr
from app.services.fallback_router import (
    _deep_research_relay,
    _dr_continue_messages,
    _dr_footer,
    route_deep_research,
    route_deep_research_stream,
    DeepResearchUnavailableError,
    _DR_CONTEXT_CHARS,
    _DR_EMPTY_MSG,
)
from app.models.schemas import MessageDto


# ─── Fakes ───────────────────────────────────────────────────────────────────

class FakeModel:
    def __init__(self, id, model_id, platform, display_name):
        self.id = id
        self.model_id = model_id
        self.platform = platform
        self.display_name = display_name


class FakeKey:
    def __init__(self, id):
        self.id = id
        self.api_key = f"sk-fake-{id}"


class FakeQuery:
    def __init__(self, rows):
        self._rows = rows

    def filter(self, *a, **k):
        return self

    def all(self):
        return self._rows


class FakeDB:
    """Returns one fake key for every ApiKey query (platform filtering is a no-op
    here — model.platform gating is what the relay actually keys off)."""
    def query(self, *a, **k):
        return FakeQuery([FakeKey(10)])


class ScriptedProvider:
    """Yields events (or raises / stalls) per model_id, consuming one scripted
    action per call. Records the order of model_ids it was called with.

    An action is one of:
      - list[dict]            → the events to yield for that call
      - Exception instance    → raised
      - "STALL"               → sleeps longer than the (patched) stall timeout
    """
    def __init__(self, script):
        self.script = {k: list(v) for k, v in script.items()}
        self.calls = []

    async def stream_chat_completion_ex(self, api_key, messages, model_id,
                                        temperature=None, max_tokens=None):
        self.calls.append(model_id)
        actions = self.script.get(model_id)
        if not actions:
            yield {"type": "finish", "reason": "stop"}
            return
        action = actions.pop(0)
        if isinstance(action, Exception):
            raise action
        if action == "STALL":
            await asyncio.sleep(5)
            return
        for ev in action:
            yield ev


def _wire(monkeypatch, provider):
    """Patch the router's collaborators so the relay runs offline."""
    monkeypatch.setattr(fr.provider_registry, "get", lambda platform: provider)
    monkeypatch.setattr(fr, "_apply_owner_scope", lambda q: q)
    monkeypatch.setattr(fr.rate_limit, "is_on_cooldown", lambda *a, **k: False)
    monkeypatch.setattr(fr.rate_limit, "record_success", lambda *a, **k: None)
    monkeypatch.setattr(fr.rate_limit, "set_cooldown", lambda *a, **k: None)
    monkeypatch.setattr(fr.rate_limit, "record_rate_limit_hit", lambda *a, **k: None)
    monkeypatch.setattr(fr.rate_limit, "is_retryable_error", lambda e: True)


async def _collect(models, provider, messages=None):
    """Drive the relay to completion; return (content, handoffs, done_event)."""
    messages = messages or [MessageDto(role="user", content="build a project")]
    content, handoffs, done = "", [], None
    async for ev in _deep_research_relay(FakeDB(), models, messages, 0.7, 512):
        if ev["type"] == "content":
            content += ev["text"]
        elif ev["type"] == "handoff":
            handoffs.append(ev["model"])
        elif ev["type"] == "done":
            done = ev
    return content, handoffs, done


def _content(text, reason):
    return [{"type": "content", "text": text}, {"type": "finish", "reason": reason}]


# ─── _dr_footer / _dr_continue_messages (pure helpers) ───────────────────────

def test_footer_zero_one_two():
    assert _dr_footer([]) == ""
    one = _dr_footer(["Model-A"])
    assert "generated by" in one and "Model-A" in one
    two = _dr_footer(["Model-A", "Model-B"])
    assert "2 models" in two and "Model-A → Model-B" in two


def test_continue_messages_empty_returns_base_unchanged():
    base = [MessageDto(role="user", content="hello")]
    out = _dr_continue_messages(base, "")
    assert len(out) == 1 and out[0].content == "hello"


def test_continue_messages_appends_workfar_and_resume_instruction():
    base = [MessageDto(role="user", content="build")]
    out = _dr_continue_messages(base, "PARTIAL WORK")
    assert len(out) == 3
    assert out[1].role == "assistant" and "PARTIAL WORK" in out[1].content
    assert out[2].role == "user" and "continue" in out[2].content.lower()


def test_continue_messages_truncates_to_context_chars():
    base = [MessageDto(role="user", content="build")]
    big = "x" * (_DR_CONTEXT_CHARS + 5000)
    out = _dr_continue_messages(base, big)
    assert len(out[1].content) == _DR_CONTEXT_CHARS


# ─── Relay core behavior ─────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_truncation_continues_same_model(monkeypatch):
    """finish_reason=length → same model resumes; only that model is credited."""
    modelA = FakeModel(1, "modelA", "p1", "Model-A-405B")
    provider = ScriptedProvider({"modelA": [
        _content("PART1. ", "length"),   # truncated → keep going on A
        _content("PART2 done.", "stop"),  # natural stop → complete
    ]})
    _wire(monkeypatch, provider)
    content, handoffs, done = await _collect([modelA], provider)
    assert content == "PART1. PART2 done."
    assert handoffs == []                       # same model → no hand-off
    assert done["models_used"] == ["Model-A-405B"]
    assert provider.calls == ["modelA", "modelA"]


@pytest.mark.asyncio
async def test_rate_limit_hands_off_and_relays_accumulated_work(monkeypatch):
    """A truncates, then A rate-limits → B receives the work-so-far and finishes."""
    modelA = FakeModel(1, "modelA", "p1", "Model-A-405B")
    modelB = FakeModel(2, "modelB", "p2", "Model-B-671B")
    provider = ScriptedProvider({
        "modelA": [_content("PART1 from A. ", "length"),
                   RuntimeError("429 rate limit exceeded")],
        "modelB": [_content("PART2 from B, done.", "stop")],
    })
    _wire(monkeypatch, provider)
    content, handoffs, done = await _collect([modelA, modelB], provider)
    assert "PART1 from A." in content and "PART2 from B, done." in content
    assert handoffs == ["Model-B-671B"]
    assert done["models_used"] == ["Model-A-405B", "Model-B-671B"]


@pytest.mark.asyncio
async def test_stall_hands_off(monkeypatch):
    """A produces no token within the stall timeout → hand off to B."""
    monkeypatch.setattr(fr, "_DR_STALL_TIMEOUT_S", 0.1)
    modelA = FakeModel(1, "modelA", "p1", "Model-A-405B")
    modelB = FakeModel(2, "modelB", "p2", "Model-B-671B")
    provider = ScriptedProvider({
        "modelA": ["STALL"],
        "modelB": [_content("Recovered by B.", "stop")],
    })
    _wire(monkeypatch, provider)
    content, handoffs, done = await _collect([modelA, modelB], provider)
    assert content == "Recovered by B."
    assert done["models_used"] == ["Model-B-671B"]


@pytest.mark.asyncio
async def test_auth_failure_skips_whole_platform(monkeypatch):
    """A 401 on platform p1 → every p1 model is skipped; only p2's model runs."""
    modelA = FakeModel(1, "modelA", "p1", "Model-A")
    modelB = FakeModel(2, "modelB", "p1", "Model-B-samePlatform")
    modelC = FakeModel(3, "modelC", "p2", "Model-C")
    provider = ScriptedProvider({
        "modelA": [RuntimeError("401 unauthorized")],
        "modelC": [_content("From C.", "stop")],
    })
    _wire(monkeypatch, provider)
    content, handoffs, done = await _collect([modelA, modelB, modelC], provider)
    assert content == "From C."
    assert done["models_used"] == ["Model-C"]
    assert "modelB" not in provider.calls          # whole p1 platform skipped


@pytest.mark.asyncio
async def test_all_models_fail_reports_no_content(monkeypatch):
    """Every model errors without output → produced_any False, no models_used."""
    modelA = FakeModel(1, "modelA", "p1", "Model-A")
    provider = ScriptedProvider({"modelA": [RuntimeError("429 quota")]})
    _wire(monkeypatch, provider)
    content, handoffs, done = await _collect([modelA], provider)
    assert content == ""
    assert done["models_used"] == []
    assert done["produced_any"] is False


# ─── Entry points + parity ───────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_empty_pool_raises_unavailable(monkeypatch):
    monkeypatch.setattr(fr, "_get_ordered_models", lambda *a, **k: [])
    msgs = [MessageDto(role="user", content="x")]
    with pytest.raises(DeepResearchUnavailableError):
        await route_deep_research(FakeDB(), msgs)
    with pytest.raises(DeepResearchUnavailableError):
        await route_deep_research_stream(FakeDB(), msgs)


@pytest.mark.asyncio
async def test_nonstream_all_fail_returns_empty_message(monkeypatch):
    modelA = FakeModel(1, "modelA", "p1", "Model-A")
    provider = ScriptedProvider({"modelA": [RuntimeError("429 quota")]})
    _wire(monkeypatch, provider)
    monkeypatch.setattr(fr, "_get_ordered_models", lambda *a, **k: [modelA])
    result = await route_deep_research(FakeDB(), [MessageDto(role="user", content="x")])
    assert result.content == _DR_EMPTY_MSG
    assert result.display_name == "Deep Research"


def _parity_script():
    return {
        "modelA": [_content("SEG_A. ", "length"),
                   RuntimeError("429 rate limit")],
        "modelB": [_content("SEG_B done.", "stop")],
    }


@pytest.mark.asyncio
async def test_streaming_and_nonstreaming_parity(monkeypatch):
    """Both entry points relay identically: same content + same models-used
    footer. Streaming additionally shows an inline hand-off marker."""
    modelA = FakeModel(1, "modelA", "p1", "Model-A-405B")
    modelB = FakeModel(2, "modelB", "p2", "Model-B-671B")
    pool = [modelA, modelB]
    monkeypatch.setattr(fr, "_get_ordered_models", lambda *a, **k: pool)
    msgs = [MessageDto(role="user", content="build a project")]

    # Non-streaming
    _wire(monkeypatch, ScriptedProvider(_parity_script()))
    non = await route_deep_research(FakeDB(), msgs)

    # Streaming (fresh provider — the script is stateful)
    _wire(monkeypatch, ScriptedProvider(_parity_script()))
    stream_res = await route_deep_research_stream(FakeDB(), msgs)
    streamed = ""
    async for chunk in stream_res.stream:
        streamed += chunk

    footer = "assembled across **2 models**: Model-A-405B → Model-B-671B"
    for text in (non.content, streamed):
        assert "SEG_A." in text and "SEG_B done." in text
        assert footer in text
    assert non.attempts == 2                     # two contributing models
    assert "Continuing with **Model-B-671B**" in streamed   # stream-only marker
    assert "Continuing with" not in non.content             # no marker non-stream
